# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = false
# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€>](bold green) """

[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green) " # The "success_symbol" segment is being set to "âœ" with the color "bold green"
format = "[$symbol$version]($style) "

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"
format = "[$symbol$version]($style) "

[[battery.display]]
threshold = 30
style = "bold red"

[time]
time_format = "%d %b, %Y | %I:%M%P "
format = "$time($style) "
style = "bright-white"
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[julia]
symbol = "à®ƒ "
format = "[$symbol$version]($style) "
style = "bold green"

[memory_usage]
symbol = "ï¡š "
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

# Disable the package module, hiding it from the prompt completely
[aws]
symbol = "îŒ½  "
format = "[$symbol$version]($style) "

[buf]
symbol = "ï’ "
format = "[$symbol$version]($style) "

[c]
symbol = "î˜ "
format = "[$symbol$version]($style) "

[conda]
symbol = "ï„Œ "
format = "[$symbol$version]($style) "

[dart]
symbol = "î˜ "
format = "[$symbol$version]($style) "

[directory]
read_only = " ï ½"
truncation_length = 8
truncation_symbol = "â€¦/"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[docker_context]
symbol = "ğŸ³ "
format = "[$symbol$version]($style) "

[elixir]
symbol = "î‰µ "
format = "[$symbol$version]($style) "

[elm]
symbol = "î˜¬ "
format = "[$symbol$version]($style) "

[git_branch]
symbol = "ï˜ "
format = "[$symbol$version]($style) "
style = "bold yellow"

[golang]
symbol = "î˜§ "
format = "[$symbol$version]($style) "

[haskell]
symbol = "î· "
format = "[$symbol$version]($style) "

[hg_branch]
symbol = "ï˜ "
format = "[$symbol$version]($style) "

[java]
symbol = "î‰– "
format = "[$symbol$version]($style) "

[lua]
symbol = "î˜  "
format = "[$symbol$version]($style) "

[meson]
symbol = "ï¨¶ "
format = "[$symbol$version]($style) "

[nim]
symbol = "ïš¤ "
format = "[$symbol$version]($style) "

[nix_shell]
symbol = "ïŒ“ "
format = "[$symbol$version]($style) "

[nodejs]
symbol = "îœ˜ "
format = "[$symbol$version]($style) "

[package]
symbol = "ï£– "
format = "[$symbol$version]($style) "

[python]
symbol = "îˆµ "
format = "[$symbol$version]($style) "

[rlang]
symbol = "ï³’ "
format = "[$symbol$version]($style) "

[ruby]
symbol = "î‘ "
format = "[$symbol$version]($style) "

[rust]
symbol = "î¨ "
format = "[$symbol$version]($style) "

[scala]
symbol = "îœ· "
format = "[$symbol$version]($style) "

[spack]
symbol = "ğŸ…¢ "
format = "[$symbol$version]($style) "
